language:
  - node_js
  - clojure
lein: lein2
jdk:
  - oraclejdk7
node_js:
  - "0.8"
before_script:
  - "echo generating the js from cljs"
  - "lein2 cljsbuild once"
  - "export DISPLAY=:99:0"      # for phantom
  - "echo 'Done.'"
script:
  - lein test && npm test
