language: node_js
node_js:
  - "0.8"
before_script:
  - "export DISPLAY=:99:0"
  - "./node_modules/buster/bin/buster-server"
  - "sleep 3"
  - "phantomjs ./node_modules/buster/script/phantom.js"
  - "sleep 3"